packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': false
  core-js: false
  protobufjs: true
  unrs-resolver: false

overrides:
  vite: npm:rolldown-vite@7.2.8
